### ISSUE TITLE
Portrait Printing cuts off "H" Day

### ISSUE THREAD

**Issue by johnnyr26** [jbis9051/Blind-Brook-Calendar-Creator#2]
<img width="508" alt="Screen Shot 2019-09-14 at 12 11 16 PM" src="https://user-images.githubusercontent.com/29236526/64910834-d83ace00-d6e8-11e9-85a4-3e348384750c.png">

When attempting to print portrait mode, "H" Day is cut off

Chrome Browser
MacOS Mojave

Also occurs in Safari

And virtually all browsers

**Comment by jbis9051** [comment]
Please edit to include your browser version and OS version.

**Comment by jbis9051** [comment]
I am not seeing issue, on same browsers and versions. Maybe something with size of cells. Can you copy and paste your schedule from eSchoolData so I can import it and test?

**Comment by johnnyr26** [comment]
A,C,D,F,G,H	1	H102	208090	Honors Algebra II/Trigonometry	1	Seeger	07/01/2019	 
A,C,D,F,G,H	2	H206	728010	Honors Computer Science	1	Kraeger	07/01/2019	 
A,B,D,E,F,G	3	H221	101030	English 10	3	Colangelo	07/01/2019	 
A,B,D,E,F,G	4	H218	308060	Honors Chemistry	2	Sugantino	07/01/2019	 
A,C,E	5	H218	308060L	Honors Chemistry lab	2	Sugantino	07/01/2019	 
B,F,H	5	H108	881063	Health	5	Carlone	07/01/2019	 
A,B,C,E,F,H	6	H219	508160	Honors Spanish 3	1	Nacher Sarris	07/01/2019	 
B,D,H	7	H GYM	801063	Tactical Sports	3	Beatty	07/01/2019	 
C,E,G	7	H210B	611093	Digital Photography	2	Buonocore	07/01/2019	 
B,C,D,E,G,H	8	H205	401020	Global History & Geography 10	5	Lewis	07/01/2019	 
A,B,C,D,F,G	9	TBD	911020	Community Service 10	2	Romm	08/21/2019

**Comment by johnnyr26** [comment]
Consider the device

Many of my peers are facing the same issue when they used your website, which is causing them to having them to reprint

**Comment by jbis9051** [comment]
Ok I am able to reproduce.

**Comment by jbis9051** [comment]
I am writing a fix. First issue is the fact that the browser doesn't break on "/". This function should pad it with spaces since spaces can be broken on.

```
 attributes[4] = attributes[4].replace(/(.?)(\/)(.?)/g, (match,$1,$2,$3) => { // this is to allow the browser to line break on "/". It pads it with spaces transforming it into " / ".
            if($1 !== "" && $1 !== " "){ // if its the beginning of the string or it already has a space skip
                $1 = $1 + " ";
            }
            if($3 !== "" && $3 !== " "){ // if its the end of the string or it already has a space skip
                $3 = " " + $3;
            }
            return $1 + $2 + $3;
        });
```
